[package]
name = "fakey-cognito"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
warp = "0.3"
tokio = { version = "1.11", features = ["full"] }
askama = "0.10"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dev-dependencies]
pretty_assertions = "0.7"
difference = "2.0"
